// Code generated by hertz generator.

package auth

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	auth "github.com/rogerogers/ops-plus/biz/model/auth"
)

// Login .
// @router /api/login/account [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req auth.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(auth.LoginReply)
	resp.Status = "ok"

	c.JSON(200, resp)
}

// Logout .
// @router /api/login/logout [POST]
func Logout(ctx context.Context, c *app.RequestContext) {
	var err error
	var req auth.LogoutReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(auth.LogoutReply)

	c.JSON(200, resp)
}
