// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/rogerogers/ops-plus/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	r.StaticFS("/", &app.FS{Root: "./web-ui/dist", GenerateIndexPages: true, IndexNames: []string{"index.html"}})
	// your code ...
}
