// Code generated by hertz generator.

package application

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	application "github.com/rogerogers/ops-plus/biz/model/application"
)

// Get .
// @router /api/application [GET]
func Get(ctx context.Context, c *app.RequestContext) {
	var err error
	var req application.ApplicationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(application.ApplicationReply)

	c.JSON(200, resp)
}
