// Code generated by hertz generator.

package user

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	user "github.com/rogerogers/ops-plus/biz/model/user"
	"github.com/rogerogers/ops-plus/internal/response"
)

// Current .
// @router /api/user/current [POST]
func Current(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.CurrentUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(user.CurrentUserReply)

	response.Success(c, resp)
}
