// Code generated by hertz generator.

package repository

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	repository "github.com/rogerogers/ops-plus/biz/model/repository"
)

// List .
// @router /api/repo/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var err error
	var req repository.RepoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(repository.RepoReply)

	c.JSON(200, resp)
}
